### ISSUE TITLE
Is this the firmware for PM981a? It worked for my PM9A1...

### ISSUE THREAD

**Issue by dingxy1996** [guosasipo/PM981a_firmware#1]
I bought a PM9A1(MZVL21T0HCLR-00BKS) with the stock firmware of GXA7AK2Q, then I found that the newly manufactured version is shipped with the firmware of GXA7CK2Q, so I got here...
But it showed here that this firmware is suitable for PM981a, after search the Internet and market, I didn't found any version of PM981a using this version of firmware, so I think maybe you wrote it wrong.
So I tried to download and running this EXE file, after reboot, the firmware of my PM9A1 successful upgraded to GXA7CK2Q from GXA7AK2Q, everything is fine, thanks to your firmware!

**Comment by dingxy1996** [comment]
I think other OEM version of PM9A1 with firmware lower than GXA7CK2Q can use this to upgrade, but not for PM9A1-00B00, this need to upgrade to GXA7401Q.

**Comment by guosasipo** [comment]
That sounds good.
